
package com.unitn.local_database;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LocalDB", targetNamespace = "http://local_database.unitn.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LocalDB {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDescription", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.GetDescription")
    @ResponseWrapper(localName = "getDescriptionResponse", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.GetDescriptionResponse")
    @Action(input = "http://local_database.unitn.com/LocalDB/getDescriptionRequest", output = "http://local_database.unitn.com/LocalDB/getDescriptionResponse")
    public String getDescription();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "saveData", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.SaveData")
    @ResponseWrapper(localName = "saveDataResponse", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.SaveDataResponse")
    @Action(input = "http://local_database.unitn.com/LocalDB/saveDataRequest", output = "http://local_database.unitn.com/LocalDB/saveDataResponse")
    public void saveData(
        @WebParam(name = "arg0", targetNamespace = "")
        MeasureData arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.unitn.local_database.MeasureData>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLatestData", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.GetLatestData")
    @ResponseWrapper(localName = "getLatestDataResponse", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.GetLatestDataResponse")
    @Action(input = "http://local_database.unitn.com/LocalDB/getLatestDataRequest", output = "http://local_database.unitn.com/LocalDB/getLatestDataResponse")
    public List<MeasureData> getLatestData(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userExists", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.UserExists")
    @ResponseWrapper(localName = "userExistsResponse", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.UserExistsResponse")
    @Action(input = "http://local_database.unitn.com/LocalDB/userExistsRequest", output = "http://local_database.unitn.com/LocalDB/userExistsResponse")
    public boolean userExists(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "totalSteps", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.TotalSteps")
    @ResponseWrapper(localName = "totalStepsResponse", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.TotalStepsResponse")
    @Action(input = "http://local_database.unitn.com/LocalDB/totalStepsRequest", output = "http://local_database.unitn.com/LocalDB/totalStepsResponse")
    public Integer totalSteps(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        long arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.unitn.local_database.UserData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.GetUserResponse")
    @Action(input = "http://local_database.unitn.com/LocalDB/getUserRequest", output = "http://local_database.unitn.com/LocalDB/getUserResponse")
    public UserData getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://local_database.unitn.com/", className = "com.unitn.local_database.CreateUserResponse")
    @Action(input = "http://local_database.unitn.com/LocalDB/createUserRequest", output = "http://local_database.unitn.com/LocalDB/createUserResponse")
    public void createUser(
        @WebParam(name = "arg0", targetNamespace = "")
        UserData arg0);

}
