
package com.unitn.local_database;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LocalDatabase", targetNamespace = "http://local_database.unitn.com/", wsdlLocation = "https://nameless-forest-62807.herokuapp.com/ws/localdb?wsdl")
public class LocalDatabase
    extends Service
{

    private final static URL LOCALDATABASE_WSDL_LOCATION;
    private final static WebServiceException LOCALDATABASE_EXCEPTION;
    private final static QName LOCALDATABASE_QNAME = new QName("http://local_database.unitn.com/", "LocalDatabase");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://nameless-forest-62807.herokuapp.com/ws/localdb?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOCALDATABASE_WSDL_LOCATION = url;
        LOCALDATABASE_EXCEPTION = e;
    }

    public LocalDatabase() {
        super(__getWsdlLocation(), LOCALDATABASE_QNAME);
    }

    public LocalDatabase(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOCALDATABASE_QNAME, features);
    }

    public LocalDatabase(URL wsdlLocation) {
        super(wsdlLocation, LOCALDATABASE_QNAME);
    }

    public LocalDatabase(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOCALDATABASE_QNAME, features);
    }

    public LocalDatabase(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LocalDatabase(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LocalDB
     */
    @WebEndpoint(name = "LocalDBImplPort")
    public LocalDB getLocalDBImplPort() {
        return super.getPort(new QName("http://local_database.unitn.com/", "LocalDBImplPort"), LocalDB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LocalDB
     */
    @WebEndpoint(name = "LocalDBImplPort")
    public LocalDB getLocalDBImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://local_database.unitn.com/", "LocalDBImplPort"), LocalDB.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOCALDATABASE_EXCEPTION!= null) {
            throw LOCALDATABASE_EXCEPTION;
        }
        return LOCALDATABASE_WSDL_LOCATION;
    }

}
